#define ERROR_MESSAGE_TOO_LONG "0"
#define ERROR_INVALID_RELAY_ID "1"
#define ERROR_INVALID_SOIL_MOISTURE_SENSOR_ID "2"

#define EVENT_ERROR "0"
#define EVENT_WARNING "1"

#define REQUEST_SET_RELAY "0"
#define REQUEST_READ_SOIL_MOISTURE "1"
#define REQUEST_GET_RELAY "2"
#define REQUEST_TOGGLE_RELAY "3"

#define EEPROM_RELAY_START 0 // length = 8 bytes
